### ISSUE TITLE
About training for1024*1024 imaging

### ISSUE THREAD

**Issue by fdujay** [LukeDitria/CNN-VAE#10]
Dear LukeDitria,
I am a long-time user of this repo and I have raised an issue about scaling to 256 resolutions earlier (if you remember). But now I want to train on much higher resolution images (1024), do you think it is possible or what necessary changes do I need to make?
Best regards,
Jay

**Comment by LukeDitria** [comment]
Hello, Yes it should be possible to run on 1024x1024 images with no change, you just need to specify the image size when running the script. Are you running into any specific problems?

**Comment by fdujay** [comment]
Thanks for reply. I'll try some experiment, if meet problem, talk later.
