### ISSUE TITLE
Question about class ResUp

### ISSUE THREAD

**Issue by zekunlou** [LukeDitria/CNN-VAE#4]
In `class Decoder`, the number of convolutional patterns decreaes (from z to ch*8 -> ch*8 -> ch*4 -> ch*2 -> ch).

In `class ResUp`, the convolution operation goes in this way: `self.conv1 = nn.Conv2d(channel_in, channel_out//2, 3, 1, 1)`.
In this way, the number of convolutional patterns is smaller than channel_out.
Take `ResUp(ch*8, ch*4)` as an example, the number of convolutional patterns varies by `ch*8 -> ch*2 ->ch*4`.

I suggest that are there any mistakes in `self.conv1` in `class ResUp`?
I think it should be `self.conv1 = nn.Conv2d(channel_in, channel_in//2,3,1,1)` or `nn.Conv2d(channel_in, channel_out*2, 3, 1, 1)` or something that doesn't "shrink" the convolutional patterns during the operation.

**Comment by LukeDitria** [comment]
Hi, 
Thanks for you comment.
Yes that is a good point, often in the residual connection it is common to down-sample to ensure that the two layers do not simply learn an identity, however only the decoder does this. It may be a good idea to make both follow the same layout, though i'm not sure it will improve performance too much, though perhaps you could reduce the number of parameters etc.
