### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by iinc** [LukeDitria/CNN-VAE#6]
Hey I just wanted to say I really like your project. I have tried out other vae repos in the past and this one is much easier to use and performs much better. I was able to very quickly get setup training on my dataset. The VGG19 model vastly improves training performance for me compared to other network structures I've used before. Code is very clean as well. Cheers!

**Comment by LukeDitria** [comment]
Thanks for the feedback! One of the reasons I made it was because I also struggled to find a good VAE implementation, so I'm glad others are finding it useful too!
